name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_NAME: BDTHPlugin
  RELEASE_NAME: BDTHPlugin
  RELEASE_DIR: BDTHPlugin\bin\Release

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

    - name: Build
      run: |
        dotnet restore -r win ${{ env.SOLUTION_NAME }}.sln
        dotnet build --configuration Release
      env:
        DOTNET_CLI_TELEMETRY_OUTPUT: true

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: PluginZip
        path: ${{ env.RELEASE_DIR }}
        if-no-files-found: error
        
  release:

    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: PluginZip

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.1

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }} ${{ env.GIT_TAG_NAME }}
          body: ${{ github.events.commits[0].message }}
          files: ${{ steps.download.outputs.download-path }}
          
      - name: Trigger plugin repo update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: LeonBlade/DalamudPlugins
          event-type: new-release
